<div class="row">
    <div class="column small-6">

        <h2>Design Your Case</h2>

        Choose Your Device
        <select>
            <option value="iPhone4">iPhone 4</option>
            <option value="iPhone5">iPhone 5</option>
            <option value="iPhone6">iPhone 6</option>
            <option value="iPhone6Plus">iPhone 6 Plus</option>
        </select>

        <button class="button">Upload Image</button>
        <br>
        <button class="button">Place Order</button>

        <ul>
            <li>Protection agnist dirt, scratches and minor bumps.</li>
            <li>High quality print graphics.</li>
            <li>Precise for for easy access to buttons and ports.</li>
            <li>High Gloss scratch resistant coating.</li>
            <li>Thermo Plastic Polymer Fusion Case</li>
        </ul>
        <button class="button">Restart Design</button>
    </div>
    <div class="column small-6">
        <img src="images/iPhn6Otline.png"
    </div>
</div>