<footer class="row expanded">
    <div class="row center">
        <div class="column text-center small-3">
            <a class="shadowfilter" href="https://goo.gl/maps/JjtpkEzSE7T2" target="_blank"><img src="images/mapwht.png"/>
            <h3>Visit</h3></a>
            <p class="hide-for-small-only">#13 Kennedy Sub.</p>
        </div>
        <div class="column text-center small-3">
            <a class="shadowfilter" href="https://www.facebook.com/Moss-Computer-Repairs-Solutions-222265561119452/" target="_blank"><img src="images/fbwht.png"/>
            <h3>Like</h3></a>
            <p class="hide-for-small-only">Facebook Moss Computer Repairs</p>
        </div>
        <div class="column text-center small-3">
            <a class="shadowfilter" href="https://www.instagram.com/mosscomputerrepair/" target="_blank"><img src="images/igwht.png"/>
            <h3>Follow</h3></a>
            <p class="hide-for-small-only">Instagram Moss Repair</p>
        </div>
        <div class="column text-center small-3">
            <a class="shadowfilter" href="tel://12425446666"><img src="images/phwht.png"/>
            <h3>Call</h3></a>
            <p class="hide-for-small-only">242-544-6666</p>
        </div>
    </div>
    <div class="row">
        <div class="column copy text-center small-centered">
            <span>Copyright&copy; <?php echo date("Y") ?> Moss Computer Repair Solutions<br>All Rights Reserved<br>Please adhere to <a href="#">Terms & Conditions</a></a></span>
        </div>
    </div>
</footer>