<div class="row icons animatedParent expanded">
    <div class="row animated bounceIn ">
        <div class="column small-3 text-center"><img src="images/brands/asus.png"/></div>
        <div class="column small-3 text-center"><img src="images/brands/sam.png"/></div>
        <div class="column small-3 text-center"><img src="images/brands/appl.png"/></div>
        <div class="column small-3 text-center"><img src="images/brands/and.png"/></div>
    </div>
    <div class="row">
        <div class="column small-3 text-center"><img src="images/brands/blu.png" /> </div>
        <div class="column small-3 text-center"><img src="images/brands/lg.png" /> </div>
        <div class="column small-3 text-center"><img src="images/brands/win.png" /> </div>
        <div class="column small-3 text-center"><img src="images/brands/hua.png" />  </div>
    </div>
</div>
