<div class="row expanded reviews snap">
    <a name="reviews"></a>
    <div class="row">
        <div class="column small-12 text-center">
            <h2 class="show-for-small-only">OUR REVIEWS</h2>
            <h2 class="show-for-medium">Hear what past clients have said</h2>
        </div>
    </div>

    <div class="row small-centered">
        <div class="testimonial-wrap">
             <div class="row ">
                <div class="large-4 columns testimonial">
                    <div class="quote">
                        <p>The service I recieved at Moss Computers was one of the best experiences ever.</p>
                    </div>
                    <div class="student hide-for-small-only">
                        <div class="photo"> </div>
                        <p>John Doe</p>
                        <p>Important person, some Company</p>
                    </div>
                </div>
                <div class="large-4 columns testimonial">
                    <div class="quote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices, elit sed faucibus pharetra, diam mauris bibendum orci, sit amet ullamcorper purus dui sit amet augue. Donec aliquet diam ut neque mattis, eu tristique sem rutrum.  </p>
                    </div>
                    <div class="student hide-for-small-only">
                        <div class="photo"> </div>
                        <p>John Doe</p>
                        <p>Important person, some Company</p>
                    </div>
                </div>
                 <div class="large-4 columns testimonial">
                     <div class="quote">
                         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultrices, elit sed faucibus pharetra, diam mauris bibendum orci, sit amet ullamcorper purus dui sit amet augue. Donec aliquet diam ut neque mattis, eu tristique sem rutrum.  </p>
                     </div>
                     <div class="student hide-for-small-only">
                         <div class="photo"> </div>
                         <p>John Doe</p>
                         <p>Important person, some Company</p>
                     </div>
                 </div>
            </div>
        </div>
        </div>
    </div>
</div>