<section class="row services small-centered">

    <div class="row small-centered">
        <div class="column small-centered text-center small-12">
            <h2>Our Services</h2><br>
            <p>we make top service our number one priority</p>
        </div>
    </div>

    <!--Slideshow of services-->
    <div class="row small-centered">
        <div class="column small-centered text-center small-12">

                    <ul id="image-gallery" class="gallery list-unstyled cS-hidden">
                        <li data-thumb="images/slides/CPthum.png">
                            <img src="images/slides/CPSlide.png" />
                        </li>
                        <li data-thumb="images/slides/WifiThum.png">
                            <img src="images/slides/WifiSlide.png" />
                        </li>
                        <li data-thumb="images/slides/PrintThum.png">
                            <img src="images/slides/PrintSlide.png" />
                        </li>
                        <li data-thumb="images/slides/AVThum.png">
                            <img src="images/slides/AVSlide.png" />
                        </li>
                        <li data-thumb="img/thumb/cS-5.jpg">
                            <img src="img/cS-5.jpg" />
                        </li>
                        <li data-thumb="img/thumb/cS-6.jpg">
                            <img src="img/cS-6.jpg" />
                        </li>
                        <li data-thumb="img/thumb/cS-7.jpg">
                            <img src="img/cS-7.jpg" />
                        </li>
                        <li data-thumb="img/thumb/cS-8.jpg">
                            <img src="img/cS-8.jpg" />
                        </li>
                        <li data-thumb="img/thumb/cS-9.jpg">
                            <img src="img/cS-9.jpg" />
                        </li>
                        <li data-thumb="img/thumb/cS-10.jpg">
                            <img src="img/cS-10.jpg" />
                        </li>
                        <li data-thumb="img/thumb/cS-11.jpg">
                            <img src="img/cS-11.jpg" />
                        </li>
                        <li data-thumb="img/thumb/cS-12.jpg">
                            <img src="img/cS-12.jpg" />
                        </li>
                        <li data-thumb="img/thumb/cS-13.jpg">
                            <img src="img/cS-13.jpg" />
                        </li>
                        <li data-thumb="img/thumb/cS-14.jpg">
                            <img src="img/cS-14.jpg" />
                        </li>
                        <li data-thumb="img/thumb/cS-15.jpg">
                            <img src="img/cS-15.jpg" />
                        </li>
                    </ul>
        </div>
    </div>

</section>