<section class="row service centered">
    <a name="services"></a>
    <div class="row small-centered">
        <div class="column small-centered text-center small-12">
            <h2>Our Services</h2>
            <p>we make top service our number one priority</p>
        </div>
    </div>

    <!--Slideshow of services-->
    <div class="row centered">
        <div class="column centered text-center small-12">

                    <ul id="image-gallery" class="gallery list-unstyled cS-hidden">
                        <li data-thumb="images/slides/CPthum.png">
                            <img src="images/slides/CPSlide.png" />
                        </li>
                        <li data-thumb="images/slides/WifiThum.png">
                            <img src="images/slides/WifiSlide.png" />
                        </li>
                        <li data-thumb="images/slides/PrintThum.png">
                            <img src="images/slides/PrintSlide.png" />
                        </li>
                        <li data-thumb="images/slides/AVThum.png">
                            <img src="images/slides/AVSlide.png" />
                        </li>
                        <li data-thumb="images/slides/HSThum.png">
                            <img src="images/slides/HSSlide.png" />
                        </li>
                        <li data-thumb="images/slides/PCThum.png">
                            <img src="images/slides/PCSlide.png" />
                        </li>
                        <li data-thumb="images/slides/POSThum.png">
                            <img src="images/slides/POSSlide.png" />
                        </li>
                        <li data-thumb="images/slides/DFThum.png">
                            <img src="images/slides/DFSlide.png" />
                        </li>
                        <li data-thumb="images/slides/HMThum.png">
                            <img src="images/slides/HMSlide.png" />
                        </li>
                    </ul>
        </div>
    </div>

</section>