<div class="topSect snap">
<!--Top Blue Bar-->
<div class="header topBar expanded">
</div>

<!--Top Section-->
<div class="expanded menuRow">
    <!--Menu and Logo Bar-->
    <div class="row small-centered small-12 column">
        <!--Logo-->
        <div class="column small-12 text-center medium-4">
            <img class="logo" alt="Moss Computer Repair Solutions"  src="images/Logo.png"/>
        </div>
        <!--Menu Bar-->
        <menu class="column hide-for-small-only medium-8">
            <div class="row">
                <ul class="menu small-11 column">
                    <li><a href="#cases" class="smoothScroll"><span>create a</span><br>CASES</a></li>
                    <li><a href="#services" class="smoothScroll"><span>learn about our</span><br>SERVICES</a></li>
                    <li><a href="#reviews" class="smoothScroll"><span>see our</span><br>REVIEWS</a></li>
                    <li><a href="#contact" class="smoothScroll"><span>get in</span><br>CONTACT</a></li>
                </ul>
                <div class="float-right text-right small-1 column">
                    <a href="https://www.facebook.com/Moss-Computer-Repairs-Solutions-222265561119452/" target="_blank"><img class="ico" src="images/fbthum.png"/></a><br><a href="https://www.instagram.com/mosscomputerrepair/" target="_blank"><img class="ico" src="images/igthum.png"/></a>
                </div>
            </div>
        </menu>
    </div>
    <!--End of Menu and Logo-->
    <!--Start of topBody-->
    <div class="row topBody">

        <div class="row surgeon">
            <div class="column text-center small-12">
                <img src="images/surgeon.png" />
            </div>
        </div>

        <div class="row">
            <div class="column text-center small-12">
                <hgroup>
                <h2>Device Feeling Down</h2>
                <h3>Bring it to The Surgeon</h3>
                <h4>Repairs for all laptops, cell phones, tablets and electronics</h4>
                </hgroup>
            </div>
        </div>

        <div class="row">
            <div class="column text-center small-12">
                <a href="#cases" class="smoothScroll"> 
                    <button onclick="#cases" class="button-lf smoothScroll">make a phone case</button>
                </a>
                <a href="#contact" class="smoothScroll">
                    <button class="button-rg">send us a message</button>
                </a>
            </div>
        </div>

    </div>
</div>
</div>